### ISSUE TITLE
有乱码呀

### ISSUE THREAD

**Issue by ppyang010** [kuckboy1994/dailyNote#4]
布局之类的地方

**Comment by kuckboy1994** [comment]
乱码已经修复。囧，你有遇到过么。 好像用vscode经常会出现

**Comment by ppyang010** [comment]
这个不知道 我一般吧vscode当文本编辑器用   写比较多的东西的发还是用atom

**Comment by kuckboy1994** [comment]
atom不得不说还是卡。 哈哈

**Comment by ppyang010** [comment]
不关就好了呀  233333333

**Comment by kuckboy1994** [comment]
你是说打开卡吗？ 
我是说写东西的时候卡。。。。。

**Comment by ppyang010** [comment]
有么  写东西一直还好呀  主要时间都在开启上呢

**Comment by kuckboy1994** [comment]
我记得上千就开始卡了，markdown 开预览上百就开始卡了。 
公司的电脑卡也是一个原因

**Comment by ppyang010** [comment]
毕竟是微软 做ide还是有一套的

**Comment by kuckboy1994** [comment]
发现有乱码。继续和我说一下 ;-)
